spring:
  application:
    name: technosky
  jpa:
    open-in-view: false
    properties.hibernate:
      hbm2ddl.auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    org.hibernate.stat: INFO
