spring:
  jpa:
    properties.hibernate:
      generate_statistics: true
      session:
        events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
      show_sql: true
      format_sql: true

logging:
  level:
    org.hibernate.stat: DEBUG
